import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/TransitionProvider";
import { Toaster } from "react-hot-toast";

const sora = Sora({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={`${sora.className} antialiased`}>
        <AuthProvider>
          {/* Background layers */}
          {/* Gradient mesh base */}
          <div className="fixed inset-0 -z-30 pointer-events-none bg-[radial-gradient(900px_circle_at_15%_10%,rgba(0,240,255,0.08),transparent_60%),radial-gradient(900px_circle_at_85%_70%,rgba(157,0,255,0.08),transparent_60%)]" />
          {/* Subtle rotating conic aura */}
          <div className="fixed inset-0 -z-20 pointer-events-none overflow-hidden">
            <div
              className="absolute left-1/2 top-1/2 h-[120vmax] w-[120vmax] -translate-x-1/2 -translate-y-1/2 rounded-full opacity-[0.07] blur-3xl animate-[slow-rotate_80s_linear_infinite] will-change-transform"
              style={{
                background:
                  "conic-gradient(from 0deg at 50% 50%, rgba(0,240,255,0.14), rgba(157,0,255,0.12), rgba(0,240,255,0.14))",
              }}
            />
          </div>
          {/* Subtle grid overlay */}
          <div className="fixed inset-0 w-full h-full bg-[url('/grid.svg')] opacity-20 -z-10 pointer-events-none" />

          <Navbar />

          <main className="relative z-10 min-h-screen pt-20 px-4">
            <TransitionProvider>{children}</TransitionProvider>
          </main>

          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "rgba(20, 20, 35, 0.7)",
                backdropFilter: "blur(10px)",
                color: "#FFFFFF",
                border: "1px solid rgba(255, 255, 255, 0.1)",
                borderRadius: "12px",
              },
              success: {
                iconTheme: {
                  primary: "#00F0FF",
                  secondary: "#000010",
                },
              },
              error: {
                iconTheme: {
                  primary: "#FF4D4D",
                  secondary: "#000010",
                },
              },
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
